-- Rebuild chat_pinned_agent to match the offical schema (MUL-4295).
--
-- The old table used a composite PK (user_id, agent_id, workspace_id) with a
-- SMALLINT sort_order. The new schema uses a UUID PK with a FLOAT position,
-- matching the offical queries generated by sqlc.

DROP TABLE IF EXISTS chat_pinned_agent;

CREATE TABLE chat_pinned_agent (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id UUID NOT NULL,
    user_id UUID NOT NULL,
    agent_id UUID NOT NULL,
    position DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
